export const gameConfig = {
  world: {
    width: 1000,
    height: 1000,
    gridStep: 100,
  },
  aircraft: {
    speed: 7.2,
    waypointArrivalRadius: 5,
  },
  loop: {
    maxDeltaSeconds: 0.05,
  },
  interaction: {
    waypointHitRadius: 18,
  },
  radar: {
    scanIntervalSeconds: 0.25,
    sweepDegreesPerSecond: 38,
    beamWidthDegrees: 24,
    baseDetectionProbability: 0.46,
    contactLifetimeMs: 8000,
    minErrorRadius: 16,
    maxErrorRadius: 85,
    operatorDecisionIntervalSeconds: 0.5,
    focusedContactMemoryMs: 4500,
    sectorContactMemoryMs: 9000,
    shutdownDurationMs: 3000,
    shutdownCooldownMs: 20000,
  },
  belief: {
    gridSize: 24,
    propagationIntervalSeconds: 0.25,
    diffusionRate: 0.16,
    decayRate: 0.992,
    evidencePersistence: 0.42,
    maxEstimatedSpeed: 100,
  },
  awareness: {
    contactGain: 16,
    signalGain: 7,
    decayPerSecond: 0.22,
    suspiciousThreshold: 18,
    searchingThreshold: 42,
    huntingThreshold: 72,
  },
  commander: {
    decisionIntervalSeconds: 1,
  },
  engagement: {
    suspectedThreshold: 16,
    trackedThreshold: 42,
    lockedThreshold: 72,
    launchThreshold: 100,
    contactGain: 12,
    decayPerSecond: 14,
    missileGuidanceBreakThreshold: 32,
    missileFlightSeconds: 8,
    hitDamage: 50,
    damagedSpeedMultiplier: 0.72,
    damagedDetectionMultiplier: 1.18,
  },
  mission: {
    attackRadius: 58,
    attackAwarenessGain: 34,
    extractionArea: { x: 850, y: 30, width: 120, height: 120 },
  },
  initialSeed: "ZERO-RETURN-001",
} as const;
